Make styling improvements
Zuretto/planning-poker pull request #19
Opened 2023-05-03 16:05 UTC by KubaZm

2023-05-03 17:11 UTC, kezc submitted a review, later dismissed

2023-05-03 17:14 UTC, Zuretto requested changes

2023-05-03 17:14 UTC, Zuretto commented on frontend/src/lib/components/MainView/MainView.svelte
> +    }
please add missing semicolons

2023-05-04 06:21 UTC, Zuretto approved these changes
GJ

2023-05-04 13:25 UTC, merged