Add endpoint for table creation
Zuretto/planning-poker pull request #3
Opened 2023-03-20 17:42 UTC by kezc

### Description
Added `PUT /table` endpoint for creating tables. It takes the creator's username as a request body.

2023-03-20 17:44 UTC, kezc commented on backend/src/main/kotlin/pl/poznan/put/tsd/planningpoker/backend/services/GamesService.kt
> +class GamesService {
note: I will add tests for this class after we implement method to retrieve single game (probably together with `/join` endpoint)

2023-03-20 18:08 UTC, Zuretto requested changes

2023-03-20 18:08 UTC, Zuretto commented on backend/src/main/kotlin/pl/poznan/put/tsd/planningpoker/backend/resources/TableResource.kt
> +@RestController
please add `/poker-api/v1` prefix to the Path (or maybe `/poker-api/v1/table-api`)

2023-03-21 20:17 UTC, Zuretto approved these changes
Wonderful

2023-03-21 20:41 UTC, KubaZm approved these changes

2023-03-23 09:40 UTC, merged